'use client';
import {useEffect,useState} from 'react';
type Member={member_id:string;role:string;email:string;created_at:string};
export default function TeamPage(){
 const [members,setMembers]=useState<Member[]>([]); const [email,setEmail]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const load=async()=>{setLoading(true);const r=await fetch('/api/team');const d=await r.json();if(r.ok)setMembers(d.members||[]);else setMessage(d.error||'Could not load team.');setLoading(false)};
 useEffect(()=>{load()},[]);
 const add=async()=>{setBusy(true);setMessage('');const r=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)setMessage(d.error||'Could not add member.');else{setEmail('');setMessage('Team member added.');await load()}setBusy(false)};
 const remove=async(id:string)=>{setBusy(true);setMessage('');const r=await fetch('/api/team',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({member_id:id})});const d=await r.json();if(!r.ok)setMessage(d.error||'Could not remove member.');else{setMessage('Team member removed.');await load()}setBusy(false)};
 return <main className="min-h-screen bg-[#f7faff]"><header className="border-b bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-4"><a href="/dashboard" className="text-xl font-black text-[#0A1E3D]">QUVOTO</a><a href="/app" className="rounded-xl bg-[#1769E0] px-4 py-2 text-sm font-bold text-white">New quote</a></div></header><section className="mx-auto max-w-3xl px-5 py-10"><p className="text-sm font-bold text-[#1769E0]">TEAM</p><h1 className="mt-1 text-4xl font-black text-[#0A1E3D]">Your QUVOTO team</h1><p className="mt-2 text-slate-500">Add up to two additional existing QUVOTO accounts. Team members share the owner's quote workspace and Team plan allowance.</p>
 {message&&<div className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm font-semibold text-amber-800">{message}</div>}
 <div className="mt-7 rounded-[2rem] border bg-white p-6 shadow-sm"><h2 className="font-black">Add a member</h2><div className="mt-3 flex gap-2"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="member@example.com" className="min-w-0 flex-1 rounded-xl border p-3"/><button disabled={busy||members.length>=2} onClick={add} className="rounded-xl bg-[#0A1E3D] px-4 font-bold text-white disabled:opacity-50">Add</button></div><p className="mt-2 text-xs text-slate-500">The person must already have a QUVOTO account.</p></div>
 <div className="mt-5 rounded-[2rem] border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black">Members</h2><span className="text-xs font-bold text-slate-400">{loading?'Loading…':(members.length+1)+'/3 users'}</span></div><div className="mt-4 space-y-3"><div className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><div><p className="font-bold">Owner</p><p className="text-sm text-slate-500">You</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-[#1769E0]">Owner</span></div>{members.map(m=><div key={m.member_id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-bold">{m.email}</p><p className="text-xs text-slate-400">Member</p></div><button disabled={busy} onClick={()=>remove(m.member_id)} className="rounded-lg border px-3 py-2 text-xs font-bold text-red-600">Remove</button></div>)}</div></div></section></main>;
}