'use client';
import { useEffect, useState } from 'react';
import { Loader2, Mail } from 'lucide-react';

function Brand(){return <div className="flex items-center gap-3"><img src="/logo.svg" alt="QUVOTO" className="h-12 w-12"/><div><div className="text-2xl font-black tracking-[-0.05em] text-[#0A1E3D]">QUVOTO</div><div className="text-[9px] font-bold uppercase tracking-[0.2em] text-[#1769E0]">Speak. Quote. Done.</div></div></div>;}
import { createClient } from '@/lib/supabase/client';

export default function LoginPage(){
  const [email,setEmail]=useState('');
  const next = typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('next') || '/app' : '/app'; const authError = typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('error') : null; const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [legal,setLegal]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setMessage('');if(!legal){setError('Please agree to the Terms of Service and acknowledge the Privacy Policy before continuing.');return;}setLoading(true);document.cookie='quvoto_legal_consent=2026-10-02; Max-Age=900; Path=/; SameSite=Lax';const supabase=createClient();const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin+'/auth/callback?next='+encodeURIComponent(next)}});if(error)setError(error.message);else setMessage('Check your email for your secure QUVOTO sign-in link.');setLoading(false)};
  useEffect(()=>{if(authError==='legal-required')setError('Please accept the Terms of Service and acknowledge the Privacy Policy before signing in.');else if(authError==='auth')setError('The sign-in link could not be completed. Please request a new one.');else if(authError==='consent-save')setError('We could not securely record your legal consent. Please try signing in again.');},[authError]); return <main className="min-h-screen bg-[#f7faff] px-4 py-8 sm:px-5 sm:py-16"><div className="mx-auto max-w-md"><a href="/" aria-label="QUVOTO home"><Brand/></a><div className="mt-8 rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm sm:rounded-[2rem] sm:p-7"><div className="mb-6"><p className="text-xs font-bold tracking-widest text-[#1769E0]">MAGIC LINK</p><h1 className="mt-2 text-3xl font-black">Sign in to QUVOTO</h1><p className="mt-2 text-slate-500">No password. We will email you a one-time secure link.</p></div><form onSubmit={submit} className="space-y-4"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="min-h-12 w-full rounded-xl border border-slate-200 px-4 py-3.5 outline-none focus:border-[#1769E0]" placeholder="you@company.com"/><button disabled={loading} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1769E0] py-3.5 font-bold text-white disabled:opacity-60">{loading?<Loader2 className="animate-spin" size={18}/>:<Mail size={18}/>}Email me a sign-in link</button><label className="flex items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm text-slate-600"><input type="checkbox" checked={legal} onChange={e=>setLegal(e.target.checked)} className="mt-1 h-4 w-4 accent-[#1769E0]" /><span>I agree to the <a href="/terms" target="_blank" rel="noreferrer" className="font-semibold text-[#1769E0] underline">Terms of Service</a> and acknowledge the <a href="/privacy" target="_blank" rel="noreferrer" className="font-semibold text-[#1769E0] underline">Privacy Policy</a>.</span></label></form>{message&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div></div></main>
}
