'use client';
import Link from 'next/link';
import { useState } from 'react';
import { Check, Lock, Mic, FileText, Gift, ShieldCheck } from 'lucide-react';
import QuvotoLogo from '@/components/QuvotoLogo';

const plans = [
 { key:'free', name:'Free', monthly:0, annual:null, detail:'5 quotes / month', features:['2 PDF templates: Modern + Classic','GBP only','English only','Public quote link','Basic customer workspace','5 quotes every month'] },
 { key:'starter', name:'Starter', monthly:19, annual:190, detail:'30 quotes / month', features:['All 5 PDF templates','GBP, USD, EUR','Custom logo + remove QUVOTO branding','Quote tracking + full stats','CSV export'] },
 { key:'pro', name:'Pro', monthly:39, annual:390, detail:'100 quotes / month', features:['Everything in Starter','10 currencies','English + Arabic + Spanish + French','Custom colors, fonts & layout controls','Advanced workspace features'] },
 { key:'team', name:'Team', monthly:79, annual:790, detail:'Unlimited quotes · 3 users', features:['Everything in Pro','3 users','All supported languages','Priority support','Team-ready workspace'] }
] as const;

export default function Pricing(){
 const [loading,setLoading]=useState(''); const [error,setError]=useState(''); const [interval,setInterval]=useState<'month'|'year'>('month'); const [legal,setLegal]=useState(false); const [discountCode,setDiscountCode]=useState('');
 const checkout=async(plan:string)=>{if(!legal){setError('Please agree to the Terms of Service and acknowledge the Privacy Policy before continuing.');return;}setLoading(plan);setError('');try{const r=await fetch('/api/billing/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,interval,discountCode:discountCode.trim()||undefined})});const d=await r.json().catch(()=>null);if(r.status===401){window.location.href='/login?next=/pricing';return}if(!r.ok)throw new Error(d?.error||'Checkout unavailable.');if(!d?.url)throw new Error('Checkout link was not returned.');window.location.href=d.url}catch(e){setError(e instanceof Error?e.message:'Checkout unavailable.')}finally{setLoading('')}};
 const shown=plans.map(p=>({...p,price:interval==='month'?p.monthly:p.annual}));
 return <main className="min-h-screen bg-[#F7FAFF] text-[#0A1E3D]">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" aria-label="QUVOTO home"><QuvotoLogo className="h-11 w-auto"/></Link><Link href="/app" className="rounded-full bg-[#1769E0] px-5 py-2.5 text-sm font-black text-white">Start free</Link></div></header>
  <section className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16">
   <div className="mx-auto max-w-3xl text-center"><div className="inline-flex items-center gap-2 rounded-full bg-[#1769E0]/5 px-3 py-1.5 text-xs font-black text-[#1769E0]"><ShieldCheck size={14}/>Simple, transparent pricing</div><h1 className="mt-5 text-4xl font-black tracking-[-.045em] sm:text-6xl">Choose the quoting plan that fits your work.</h1><p className="mt-4 text-lg leading-8 text-slate-500">Start on Free. Upgrade only when you need more quotes, customization, tracking or team features.</p></div>
   <div className="mx-auto mt-6 max-w-3xl rounded-2xl border border-[#1769E0]/15 bg-white p-4 text-center text-sm font-semibold text-slate-600 shadow-sm"><b className="text-[#0A1E3D]">Referral rewards:</b> 10 qualified Free referrals unlock 1 Starter month. Monthly paid referrals use independent Starter / Pro / Team counters: 1, then every 2 additional referrals = 1 free month. Annual counters: 2 = 1 free year, 4 = 6 months, 6 = 6 months, 8 = 1 free year, then repeat.</div>
   <div className="mt-7 flex justify-center"><div className="inline-flex rounded-full border border-slate-200 bg-white p-1 shadow-sm"><button onClick={()=>setInterval('month')} className={'rounded-full px-6 py-2.5 text-sm font-black '+(interval==='month'?'bg-[#0A1E3D] text-white':'text-slate-500')}>Monthly</button><button onClick={()=>setInterval('year')} className={'rounded-full px-6 py-2.5 text-sm font-black '+(interval==='year'?'bg-[#1769E0] text-white':'text-slate-500')}>Annual</button></div></div>
   <div className="mx-auto mt-7 max-w-2xl space-y-3"><div className="rounded-2xl border border-slate-200 bg-white p-4 text-sm text-slate-600 shadow-sm"><label className="flex items-start gap-3"><input type="checkbox" checked={legal} onChange={e=>setLegal(e.target.checked)} className="mt-1 h-4 w-4 accent-[#1769E0]"/><span>I agree to the <Link href="/terms" className="font-semibold text-[#1769E0] underline">Terms of Service</Link> and acknowledge the <Link href="/privacy" className="font-semibold text-[#1769E0] underline">Privacy Policy</Link> before purchasing a paid plan.</span></label></div><input value={discountCode} onChange={e=>setDiscountCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''))} maxLength={64} placeholder="Discount code (optional)" className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 text-sm font-semibold uppercase tracking-wide outline-none focus:border-[#1769E0]"/></div>
   <div className="mt-10 grid gap-5 lg:grid-cols-4">{shown.map((p,i)=><div key={p.key} className={'relative rounded-[2rem] border bg-white p-6 shadow-sm '+(i===1?'border-[#2F8CFF] ring-4 ring-[#2F8CFF]/10':'border-slate-200')}>
    {i===1&&<span className="absolute -top-3 left-6 rounded-full bg-[#1769E0] px-3 py-1 text-[11px] font-black text-white">Most popular</span>}
    <p className="text-sm font-black text-slate-400">{p.name}</p><div className="mt-4 flex items-end gap-1"><span className="text-5xl font-black">{p.price===null?'—':p.price===0?'$0':'$'+p.price}</span>{p.price!==null&&p.price!==0&&<span className="pb-1 text-sm font-bold text-slate-400">/{interval==='month'?'mo':'yr'}</span>}</div><p className="mt-2 font-bold text-slate-700">{p.detail}</p>{interval==='year'&&p.annual&&<p className="mt-1 text-xs font-semibold text-slate-400">${Math.round(p.annual/12)}/month equivalent</p>}
    <button onClick={()=>p.key==='free'?window.location.href='/app':checkout(p.key)} disabled={!!loading} className="mt-6 block w-full rounded-xl bg-[#0A1E3D] py-3.5 text-center font-black text-white disabled:opacity-60">{loading===p.key?'Opening checkout…':p.key==='free'?'Start free':'Choose '+p.name}</button>
    <div className="mt-7 space-y-3">{p.features.map(f=><div key={f} className="flex gap-2 text-sm leading-5 text-slate-600"><Check size={16} className="mt-0.5 shrink-0 text-[#1769E0]"/>{f}</div>)}</div>
    <div className="mt-7 rounded-2xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">{p.key==='free'?'No credit card required. Upgrade when you need more.':'Your subscription remains on the plan you purchase. Referral rewards add free time; they do not silently change your plan.'}</div>
   </div>)}</div>
   {error&&<div className="mx-auto mt-6 max-w-xl rounded-2xl bg-red-50 p-4 text-center text-sm font-semibold text-red-700">{error}</div>}
   <div className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-3xl border border-slate-200 bg-white p-6"><Mic className="text-[#1769E0]"/><h2 className="mt-4 text-xl font-black">Voice-first workflow</h2><p className="mt-2 text-sm leading-6 text-slate-500">Record → transcribe → extract → review → quote.</p></div><div className="rounded-3xl border border-slate-200 bg-white p-6"><FileText className="text-[#1769E0]"/><h2 className="mt-4 text-xl font-black">Professional PDFs</h2><p className="mt-2 text-sm leading-6 text-slate-500">Modern, Classic, Bold, Minimal and Technical templates.</p></div><div className="rounded-3xl border border-slate-200 bg-white p-6"><Lock className="text-[#1769E0]"/><h2 className="mt-4 text-xl font-black">Customer workspace</h2><p className="mt-2 text-sm leading-6 text-slate-500">Every account gets a private dashboard after secure sign-in.</p></div></div>
  </section>
 </main>;
}
