'use client';
import {useEffect,useState} from 'react';
import {Copy,Gift,Package,Users,BriefcaseBusiness,Clock3} from 'lucide-react';

export default function WorkspacePage(){
 const [data,setData]=useState<any>({customers:[],savedItems:[],templates:[],jobs:[],followups:[],referrals:[],rewards:[]});
 const [ref,setRef]=useState<any>(null); const [tab,setTab]=useState('overview'); const [message,setMessage]=useState('');
 const load=async()=>{const r=await fetch('/api/workspace');if(r.ok)setData(await r.json());const rr=await fetch('/api/referrals');if(rr.ok)setRef(await rr.json())};
 useEffect(()=>{load()},[]);
 const post=async(body:any)=>{setMessage('');const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)setMessage(d.error||'Could not save.');else{setMessage('Saved.');await load()}};
 const [item,setItem]=useState({description:'',unit:'item',price:'',kind:'material'});
 const [template,setTemplate]=useState({name:'',items:'',notes:''});
 const [customer,setCustomer]=useState({name:'',email:'',phone:'',address:''});
 const tabs=[['overview','Overview'],['customers','Customers'],['items','Saved items'],['templates','Templates'],['jobs','Jobs'],['followups','Follow-ups'],['referrals','Refer & Earn']];
 return <main className="min-h-screen bg-[#f7faff] text-[#0A1E3D]"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-8"><a href="/dashboard" className="text-xl font-black tracking-[-.04em]">QUVOTO</a><div className="flex items-center gap-2"><a href="/rewards" className="rounded-xl bg-[#1769E0]/10 px-4 py-2.5 text-sm font-bold text-[#1769E0]">Rewards</a><a href="/app" className="rounded-xl bg-[#1769E0] px-4 py-2.5 text-sm font-bold text-white">New quote</a></div></div></header>
 <section className="mx-auto max-w-6xl px-4 py-7 sm:px-8"><p className="text-sm font-bold tracking-widest text-[#1769E0]">WORKSPACE TOOLS</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">Everything after the quote</h1><p className="mt-2 text-slate-500">Customers, reusable items, jobs, reminders and referrals without turning QUVOTO into a heavy CRM.</p>
 <div className="mt-6 flex gap-2 overflow-x-auto pb-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={'whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold '+(tab===id?'bg-[#0A1E3D] text-white':'bg-white text-slate-600 border')}>{label}</button>)}</div>
 {message&&<div className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}
 {tab==='overview'&&<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Customers',data.customers.length,Users],['Saved items',data.savedItems.length,Package],['Jobs',data.jobs.length,BriefcaseBusiness],['Follow-ups',data.followups.filter((x:any)=>x.status==='pending').length,Clock3]].map(([label,count,Icon]:any)=><div key={label} className="rounded-3xl border bg-white p-6"><Icon className="text-[#1769E0]"/><p className="mt-5 text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-3xl font-black">{count}</p></div>)}</div>}
 {tab==='customers'&&<div className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><FormCard title="Add customer"><input className="input" placeholder="Name" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/><input className="input" placeholder="Email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/><input className="input" placeholder="Phone" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/><textarea className="input min-h-20" placeholder="Address" value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/><button className="btn" onClick={()=>post({action:'customer',...customer})}>Save customer</button></FormCard><ListCard title="Customer history">{data.customers.map((c:any)=><a key={c.id} href={'/customers/'+c.id} className="block rounded-xl border p-4 hover:border-[#2F8CFF]"><p className="font-bold">{c.name}</p><p className="text-sm text-slate-500">{c.email||c.phone||'No contact details'}</p></a>)}</ListCard></div>}
 {tab==='items'&&<div className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><FormCard title="Quick saved item"><input className="input" placeholder="22mm copper pipe" value={item.description} onChange={e=>setItem({...item,description:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input className="input" placeholder="Unit" value={item.unit} onChange={e=>setItem({...item,unit:e.target.value})}/><input className="input" type="number" placeholder="Price" value={item.price} onChange={e=>setItem({...item,price:e.target.value})}/></div><select className="input" value={item.kind} onChange={e=>setItem({...item,kind:e.target.value})}><option value="material">Material</option><option value="labour">Labour</option><option value="service">Service</option><option value="other">Other</option></select><button className="btn" onClick={()=>post({action:'saved_item',...item})}>Save item</button></FormCard><ListCard title="My common items">{data.savedItems.map((x:any)=><div key={x.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-bold">{x.description}</p><p className="text-xs text-slate-500">{x.kind} · {x.unit}</p></div><b>{x.currency} {Number(x.price).toFixed(2)}</b></div>)}</ListCard></div>}
 {tab==='templates'&&<div className="mt-6 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><FormCard title="Reusable quote template"><input className="input" placeholder="My Boiler Replacement Quote" value={template.name} onChange={e=>setTemplate({...template,name:e.target.value})}/><textarea className="input min-h-28" placeholder='Items JSON' value={template.items} onChange={e=>setTemplate({...template,items:e.target.value})}/><textarea className="input min-h-20" placeholder="Notes, one per line" value={template.notes} onChange={e=>setTemplate({...template,notes:e.target.value})}/><button className="btn" onClick={()=>{try{post({action:'template',name:template.name,items:JSON.parse(template.items||'[]'),notes:template.notes.split('\n').filter(Boolean),currency:'GBP'})}catch{setMessage('Items JSON is invalid.')}}}>Save template</button></FormCard><ListCard title="My quote templates">{data.templates.map((x:any)=><div key={x.id} className="rounded-xl border p-4"><p className="font-bold">{x.name}</p><p className="mt-1 text-xs text-slate-500">{Array.isArray(x.items)?x.items.length:0} reusable line items</p></div>)}</ListCard></div>}
 {tab==='jobs'&&<ListCard title="Jobs"><div className="space-y-3">{data.jobs.map((j:any)=><div key={j.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><b>{j.title}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{j.status}</span></div><p className="mt-1 text-xs text-slate-500">{new Date(j.created_at).toLocaleDateString()}</p></div>)}{!data.jobs.length&&<p className="text-slate-500">Accepted quotes will appear here as jobs.</p>}</div></ListCard>}
 {tab==='followups'&&<ListCard title="Follow-up reminders"><div className="space-y-3">{data.followups.map((f:any)=><div key={f.id} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><b>{f.quotes?.quote_number||'Quote'}</b><span className={'rounded-full px-2 py-1 text-xs font-bold '+(f.status==='pending'?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700')}>{f.status}</span></div><p className="mt-1 text-sm text-slate-500">{f.quotes?.client_name||''} · {new Date(f.scheduled_for).toLocaleString()}</p><p className="mt-2 text-sm">{f.note}</p>{f.status==='pending'&&<button onClick={()=>post({action:'followup_done',id:f.id})} className="mt-3 rounded-lg border px-3 py-2 text-xs font-bold">Mark done</button>}</div>)}{!data.followups.length&&<p className="text-slate-500">Schedule a follow-up from a sent quote.</p>}</div></ListCard>}
 {tab==='referrals'&&<><div className="mt-6 mb-3 rounded-2xl border border-[#1769E0]/15 bg-[#1769E0]/5 p-4"><a href="/rewards" className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-widest text-[#1769E0]">New: QUVOTO Rewards</p><p className="mt-1 text-sm font-semibold text-slate-600">Three reward tracks: 10 active Free users = 1 Starter month; monthly paid referrals start at 1 and repeat every 3; annual paid referrals unlock the larger 2 / 4 / 8+ milestones.</p></div><span className="rounded-xl bg-[#1769E0] px-4 py-2 text-xs font-bold text-white">See rewards</span></a></div><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl bg-[#0A1E3D] p-6 text-white"><Gift className="text-blue-300"/><h2 className="mt-5 text-2xl font-black">Refer & Earn</h2><p className="mt-2 text-slate-300">Three reward tracks: 10 active Free users = 1 free Starter month. Monthly paid referrals: 1 same-plan referral = 1 free month, then every 3 additional referrals. Annual paid referrals: 2 = 1 free year; 4 = 6 months; 8 = 1 year, then the agreed cycle.</p>{ref&&<><div className="mt-5 rounded-2xl bg-white/10 p-4"><p className="text-xs font-bold text-slate-300">YOUR LINK</p><p className="mt-1 break-all text-sm font-semibold">{ref.link}</p><div className="mt-3 flex gap-2"><button onClick={()=>navigator.clipboard?.writeText(ref.link)} className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-[#0A1E3D]"><Copy size={14}/></button><button onClick={()=>navigator.share?.({title:'QUVOTO',text:'Try QUVOTO',url:ref.link})} className="rounded-xl bg-[#1769E0] px-3 py-2 text-xs font-bold text-white">Share</button></div></div><div className="mt-4 text-sm text-slate-300">{ref.freeCount || 0}/10 Free users toward the next Starter month · {ref.qualifiedCount} qualified annual referrals · {ref.nextMilestone ? `annual next reward at ${ref.nextMilestone}` : 'annual milestones currently complete'}</div></>}</div><ListCard title="Rewards">{(ref?.rewards||[]).map((r:any)=><div key={r.id} className="rounded-xl border p-4"><p className="font-bold">{r.reward_type==='free_year'?'1 free year':'6 free months'} · {r.plan}</p><p className="text-xs text-slate-500">{r.status} · milestone {r.milestone}</p></div>)}{!(ref?.rewards||[]).length&&<p className="text-slate-500">Your first reward is earned when 2 same-plan annual referrals actually pay.</p>}</ListCard></div></>}
 </section></main>
}
function FormCard({title,children}:{title:string;children:any}){return <div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-black">{title}</h2><div className="mt-4 space-y-3">{children}</div></div>}
function ListCard({title,children}:{title:string;children:any}){return <div className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-black">{title}</h2><div className="mt-4 space-y-3">{children}</div></div>}